<div>
    <h2>[[+name]]</h2>
    <h5>[[+description]]</h5>
    <table>
        <thead>
            <tr>
                [[+headerRow]]
            </tr>
        </thead>
        <tbody>
        [[+sessionRows]]
        </tbody>
    </table>
</div>